version: "3.7"
services:
    mongo:
      container_name: my_mongo
      image: mongo
      environment:
        - MONGO_INITDB_DATABASE=mydb
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=rootpass
      volumes:
        - mongodb_data_container:/data/db
      ports:
        - 27017:27017
        