version: "3.3"
services:
    mongo:
      container_name: mongo
      image: mongo
      command: mongod --smallfiles
      restart: always
      volumes:
        - /data/mongodb:/data/db
      ports:
        - "27017:27017" 
        